services:
  app:
    build:
      context: ./app
    container_name: py-app
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 8s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - docker_net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
#    depends_on:
#      app:
#        condition: service_healthy
    networks:
      - docker_net
networks:
  docker_net:
