name: CI infra
run-name: check infra ${{ github.repository }}

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - 'nginx/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'
jobs:
  docker-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Create .env
        run: |
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Build and Start containers
        run: docker compose up -d

      - name: check env
        run: docker compose config

      - name: curl localhost
        run: |
         for i in {1..5}; do
           if curl --fail http://localhost > /dev/null; then
             echo "Flask is up!"
             exit 0
           else
             sleep 2
           fi
         done

         echo "Flask not ready!"
         exit 1

      - name: test db connection
        run: |
          docker compose exec -T app pytest tests/test_db.py
