name: CI
run-name: "Ripository: ${{ github.repository }} Branch: ${{ github.ref_name }}"
on: [push]
jobs:
#  test-code:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#
#      - name: Set up python
#        uses: actions/setup-python@v6
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#
#      - name: Install dependencies
#        run: |
#          python3 -m pip install -r app/requirements.txt
#
#      - name: Run pytest
#        run: |
#          cd app && python3 -m pytest
#
  docker-up:
    runs-on: ubuntu-latest
#    needs: test-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Start containers
        run: docker compose up -d --build

      - name: curl localhost
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost; then
              echo "Flask is up!"
              break
            else
              echo "Flask not ready yet, retrying..."
              sleep 2
            fi
          done
